version: '3.7'

services:

  db:
    build: db
    command: postgres -c max_wal_size=2GB
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: omop
    shm_size: 5g
    volumes:
      - db-data:/var/lib/postgresql/data
      - /etc/localtime:/etc/localtime:ro

  broadsea-methods-library:
    image: ohdsi/broadsea-methodslibrary
    ports:
      - 8787:8787
      - 6311:6311
    environment:
      - PASSWORD=mypass
    depends_on:
      - db

  broadsea-webtools:
    image: ohdsi/broadsea-webtools
    ports:
      - 8080:8080
    volumes:
     - .:/tmp/drivers/:ro
     - ./config-local.js:/usr/local/tomcat/webapps/atlas/js/config-local.js:ro
    environment:
      - WEBAPI_URL=http://localhost:8080
      - env=webapi-postgresql
      - datasource_driverClassName=org.postgresql.Driver
      - datasource_url=jdbc:postgresql://db:5432/omop
      - datasource.cdm.schema=cdm
      - datasource.ohdsi.schema=ohdsi
      - datasource_username=user
      - datasource_password=password
      - spring.jpa.properties.hibernate.default_schema=ohdsi
      - spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect
      - spring.batch.repository.tableprefix=ohdsi.BATCH_
      - flyway_datasource_driverClassName=org.postgresql.Driver
      - flyway_datasource_url=jdbc:postgresql://db:5432/omop
      - flyway_schemas=ohdsi
      - flyway.placeholders.ohdsiSchema=ohdsi
      - flyway_datasource_username=user
      - flyway_datasource_password=password
      - flyway.locations=classpath:db/migration/postgresql
    depends_on:
      - db

volumes:
  db-data:
